### ISSUE TITLE
✅ 1.0 Checklist

### ISSUE THREAD

**Issue by bennymi** [bennymi/ato-ui#123]
## Stuff
- [ ] all components in Svelte 5

## UnoCSS
- [ ] buttons
- [ ] notification banners
- [ ] cards
- [ ] chips
- [ ] spinners
- [ ] ...

## Designer
- [ ] ...

## Components
- [ ] accordion (Melt UI)
- [ ] avatar (Melt UI)
- [ ] calendar (Melt UI)
- [ ] collapsible (Melt UI)
- [ ] color picker
- [ ] combobox (Melt UI)
- [ ] context menu (Melt UI)
- [ ] dialog (Melt UI)
  - [ ] add trigger to dialog
- [ ] drawer (Melt UI)
- [ ] dropdown menu (Melt UI)
- [ ] menubar (Melt UI)
- [ ] navigation menu (Melt UI)
- [ ] pagination (Melt UI)
- [ ] pin input (Melt UI)
- [ ] popover (Melt UI)
- [ ] progress (Melt UI)
- [ ] radio group (Melt UI)
- [ ] select (Melt UI)
- [ ] slider (one or multiple drag buttons) (Melt UI)
- [ ] sortable (Melt UI)
- [ ] switch (Melt UI)
- [ ] table of contents (Melt UI)
- [ ] tabs (Melt UI)
- [ ] tags input (chips) (Melt UI)
- [ ] timeline
- [ ] toast (Melt UI)
- [ ] toggle + toggle group (Melt UI)
- [ ] toolbar (Melt UI)
- [ ] tooltip (Melt UI)
- [ ] tree view (Melt UI)
- [ ] tree select (Melt UI)
- [ ] ...

## Integration into other libraries
- [ ] tables
- [ ] charts
- [ ] ...

## Other
- [ ] consistent look across components
- [ ] dark / light support out of the box for every component
- [ ] some extra features for styled components
