### ISSUE TITLE
Setup config files (eslint, tsconfig, vscode) for common project styling among contributors

### ISSUE THREAD

**Issue by bennymi** [bennymi/ato-ui#33]
I want to get rid of prettier and simply have everything defined in ESLint.

**TODOs**
- [X] Setup eslint for Svelte plugin mentioned in **Resources**
- [X] set up `airbnb` eslint style guide
- [X] changes should be made when file is saved (for contributors as well, so if a VSCode extension is needed it should be mentioned in the contributors guide)
- [X] also set up tsconfig (check this video https://www.youtube.com/watch?v=cCO0OkDUGCs)
- [X] setup `.vscode` folder with recommendation for extensions that should be installed
  - [X] UnoCSS
  - [X] Tailwind CSS
  - [X] WindiCSS
- [ ] set up lint-staged

**Resources:**
- https://github.com/sveltejs/eslint-plugin-svelte
- https://www.youtube.com/watch?v=cCO0OkDUGCs
- https://github.com/CodingGarden/listd
- use `airbnb/base` and `airbnb-typescript/base`: https://github.com/airbnb/javascript
- https://github.com/okonet/lint-staged
- Coding Garden `lint-staged`: https://www.youtube.com/watch?v=Rf9Z_arma4o
- https://stackoverflow.com/questions/62277286/eslint-in-vscode-not-fixing-on-save
- https://typescript-eslint.io/rules/naming-convention/
