### ISSUE TITLE
📖 Documentation

### ISSUE THREAD

**Issue by bennymi** [bennymi/ato-ui#35]
**TODOs**
- [x] modal (dialog)
- [ ] chips
- [ ] cards
- [ ] landing page
- [ ] use transition API across documentation 
  - https://www.youtube.com/watch?v=MJHO6FSioPI
  - PR 9605 in sveltekit repo
- [ ] edit on github link
- [ ] version and link to changelog and contribution instructions in navbar
- [ ]  last updated date time (https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28#list-commits-on-a-repository)

**Getting Started**
- [x] installation
- [ ] setup: presets, tailwind reset, import `uno.css` file (serves as a file that the css will be loaded into), etc.
- [ ] template
- [ ] transferring from Tailwind
- [x] VSCode set up (install UnoCSS extension, disable other extensions, etc)

**Shortcut Search**
- [x] search bar
- [ ] filter buttons (button, gradient, spinners, background, light / dark, etc.)
- [ ] explanation window

**Buttons**
- [x] regular (one color)
- [x] gradients (2 & 3) (mention opacity values and optional shades and so on)
- [x] glass
- [x] group (regular & outline)

**Spinners**
- [x] mention how they can be customized

**Inspiration**
- https://github.com/nuxt-themes/docus
- https://unocss.dev/
- https://vitepress.dev/
- 

**Code Blocks**
- see if we can add highlight lines to code blocks
- add shiki-twoslash (https://github.com/shikijs/twoslash)
- #74 

**Resources**
- https://github.com/vuejs/vitepress/tree/481a6e9cbd84068cc976db1e9adbc466b6e81ad9/src/client/theme-default/components
- Components to help create our own:
  - https://www.shadcn-svelte.com/docs/components/accordion

**Comment by bennymi** [comment]
Update the documentation navbar so that on mobile its at the bottom like in Svelte's documentation site.
