### ISSUE TITLE
📖 Documentation Structure

### ISSUE THREAD

**Issue by bennymi** [bennymi/ato-ui#63]
- Relates to #35.
- Relates to #74 
- Relates to #76 

**TODOs**
- [X] Navbar
- [X] Nav sidebar
- [X] table of contents for page (#67)
- [X] dark/light toggle (https://codepen.io/gvissing/pen/OJvxoJq)
- [x] themes
- [x] make sidebar groups hideable
- [X] bottom navigation (last and next page)
- [ ] edit on github link
- [ ] last updated date time (https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28#list-commits-on-a-repository)
- [X] import `BROWSER` instead of `browser` in ToC: https://kit.svelte.dev/docs/packaging
- [X] clean up the svelte ToC component
- [x] ToC should have similar structure as in vitepress
- [X] fix issues with children not being highlighted in ToC
- [X] properly place ToC in documentation
- [X] update documentation pages to be able to have both a `headless` and `styled` page
- [ ] make sure there is no horizontal scroll bar
- [x] mobile friendly: 
  - [x] sidebar and ToC should be hidden on smaller screens but still be available through buttons

**Examples**
- https://vitepress.dev/guide/what-is-vitepress#use-cases

**Hamburger menu animations**
- https://codepen.io/Zaku/pen/ejLNJL
- https://codepen.io/ainalem/pen/LJYRxz
- https://codepen.io/designcouch/pen/ExvwPY

**Resources**
- https://www.youtube.com/results?search_query=typescript+define+return+type+of+function
- https://stackoverflow.com/questions/29404093/css-outline-left-and-right
- https://svelte.dev/repl/dac9457f4e2a4ad082347ccf32d860b5?version=3.29.4
- https://github.com/vuejs/vitepress/tree/481a6e9cbd84068cc976db1e9adbc466b6e81ad9/src/client/theme-default/components
- https://github.com/vuejs/vitepress/blob/481a6e9cbd84068cc976db1e9adbc466b6e81ad9/docs/.vitepress/config.ts
- https://github.com/CaptainCodeman/svelte-headlessui/blob/master/packages/lib/src/lib/dialog.ts
-
