### ISSUE TITLE
✨ Tokens

### ISSUE THREAD

**Issue by bennymi** [bennymi/ato-ui#9]
Inverse tokens use different color for light and dark mode. You can create some dynamic shortcuts for these. For example:

`'text-inverse-primary(-<num>)-secondary(-<num>)': 'text-primary-500 dark:text-secondary-500'`

**TODOs**
- [x] inverse tokens
- [x] theme classes that set both the background and the text color
  -  Example: `primary-500 = bg-primary-500 text-on-primary-500` (https://youtu.be/RhScu3uqGd0?t=1272)
- [x] text on color should be used in most cases to make sure accessibility is always the best it can be automatically
- [x] update gradient background tokens to start with `bg-gradient-...` (consistent naming across all tokens)
- [ ] think about what should be supported for each token. Do some tokens need opacity for example? It makes it a bit complicated to set the text colors.
